---
# handlers file for apache_httpd
- name: restart apache webserver
  service:
    name: httpd
    state: restarted
  listen: "restart_apache"

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  listen: "restart_firewalld"
