---
# tasks file for db_servers
- name: install mariadb server
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "RedHat"

- name: install mariadb server
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
